In [1]:
import sympy as sym
import numpy as np
sym.init_printing()
from IPython.display import display,Math
from sympy.abc import x,y
import math
from math import gcd
x,y = sym.symbols('x,y')
import matplotlib.pyplot as plt
import sympy.plotting.plot as symplot
x,a = sym.symbols('x,a')
from matplotlib.patches import Polygon
from matplotlib import pyplot as plt
import cmath as cm
import scipy as sp
from scipy.signal import find_peaks
import seaborn as sns
from plotly.subplots import make_subplots
from plotly import graph_objects as go
from mpl_toolkits.mplot3d import Axes3D

In [2]:
A = np.random.randn(14,10)
B = np.random.randn(14,10)
C = np.random.randn(10,14)

# 10x14 14x10

C@B

array([[-1.66251992e+00,  3.37869966e+00,  5.05717884e+00,
         2.05558933e+00,  5.71123244e+00, -1.22669708e+00,
         1.14808107e-01,  3.38391878e-01, -9.78052924e-01,
        -4.42510362e-01],
       [ 6.68942393e+00, -8.00291868e+00, -1.37929594e+00,
        -2.88802862e+00,  2.33161411e+00,  3.81058375e-01,
         3.09288786e+00,  7.60861094e-01, -9.24629235e-01,
        -1.10177797e+00],
       [-1.98446106e+00, -5.34829103e+00,  1.18231911e-02,
         1.53368502e+00,  2.77683599e+00,  2.12665046e+00,
        -1.96066512e+00,  1.10614584e+00,  4.37963300e+00,
        -7.54675819e+00],
       [ 2.99572218e+00, -1.21275742e+01, -8.54809654e+00,
        -1.86145671e+00, -1.63883588e-01,  1.96073836e+00,
         3.17545029e+00,  3.49167386e+00, -9.61531848e-01,
        -4.77011069e-01],
       [ 4.51968234e+00, -8.15874148e-01, -1.07740321e+00,
         1.33784728e+00,  3.24869302e+00, -1.18588924e+00,
         2.38911415e+00,  3.84082122e+00,  1.52775832e+00,
         7.

In [3]:
A = np.random.randn(14,10)
B = np.random.randn(14,10)
C = np.random.randn(10,14)

# 10x14 14x10

np.shape(C@B)

In [4]:
A = np.random.randn(14,10)
B = np.random.randn(14,10)
C = np.random.randn(10,14)

# 10x14 14x10

np.shape(B@C)

# Exercise

Write a function that takes two matrices as input,cehcks whether multplication is valid,and returns their product or an error message.

#Note

implement matrix multiplication via dot products of rows aand columns;don't use the @ operator!

In [2]:
def matrixMultiplication(A,B):

    #get matrix sizes
    szA = np.shape(A)
    szB = np.shape(B)

    # check sizes and give error if multiplication is not valid
    if szA[1]!=szB[0]:
        raise ValueError('"Inner" dimension don\'t match')
    
    #initialize
    C = np.zeros((szA[0],szB[1]))

    #compute!
    for i in range(szA[0]):
        for j in range(szB[1]):
            C[i,j] = np.dot( A[i,:],B[:,j])
        
    return C

In [9]:
A = np.random.randn(4,6)
B = np.random.randn(6,4)

C = matrixMultiplication(A,B)
C

array([[ 1.37685167, -1.10978472, -2.59790722,  0.59813389],
       [ 3.27235649, -1.47598864, -4.81642505, -0.85983048],
       [ 1.71868747,  1.00078418, -1.00048534,  2.13073981],
       [-0.50369019,  0.8247648 ,  1.43123399,  0.24934802]])

In [4]:
A = np.random.randn(4,6)
B = np.random.randn(6,4)

C1 = matrixMultiplication(A,B)
C2 = A@B

print(np.round(C1-C2,3))

[[-0.  0.  0.  0.]
 [ 0. -0.  0.  0.]
 [ 0.  0.  0.  0.]
 [-0. -0. -0.  0.]]


In [5]:
A = np.random.randn(4,6)
B = np.random.randn(6,4)

C1 = matrixMultiplication(A,B)
C2 = A@B

print(C1)
print(np.round(C1-C2,3))

[[ 2.73617972  0.57823892  0.74281331 -4.76617852]
 [-2.62006015 -1.95773413 -1.07839585  0.94196686]
 [-0.62658397 -3.95955271  1.47428599 -0.59177524]
 [-0.62878038 -2.39005831 -1.44496307 -0.0309083 ]]
[[ 0.  0.  0.  0.]
 [-0.  0.  0.  0.]
 [ 0.  0. -0. -0.]
 [ 0. -0.  0. -0.]]
