In [6]:
import sympy as sym
import numpy as np
sym.init_printing()
from IPython.display import display,Math
from sympy.abc import x,y
import math
from math import gcd
x,y = sym.symbols('x,y')
import matplotlib.pyplot as plt
import sympy.plotting.plot as symplot
x,a = sym.symbols('x,a')
from matplotlib.patches import Polygon
from matplotlib import pyplot as plt
import cmath as cm
import scipy as sp
from scipy.signal import find_peaks
import seaborn as sns
from plotly.subplots import make_subplots
from plotly import graph_objects as go
from mpl_toolkits.mplot3d import Axes3D

In [7]:
v = np.arange(10,20,3)
v

array([10, 13, 16, 19])

In [10]:
v = np.arange(10,20,3)
w = np.arange(5,15,3)

print(v)
print(w)

dp1 = 0
for i in range(0,len(v)):
    dp1 = dp1 + v[i] * w[i]

[10 13 16 19]
[ 5  8 11 14]


In [13]:
v = np.arange(10,20,3)
w = np.arange(5,15,3)

dp1 = 0
for i in range(0,len(v)):
    dp1 = dp1 + v[i] * w[i]

dp2 = np.sum(np.multiply(v,w))
dp3 = np.dot(v,w)

print(dp1,dp2,dp3)

596 596 596


# Exericse 

write a function that:

* Takes two vectors;

* Test whether the dot product is valid between them;

* Returns the dot product or gives an error message.

In [14]:
def myDotProduct(v,w):

    #test whether the dot is defined
    if len(v)!=len(w):
        raise ValueError('Vector must have the same length!!')
    
    # compute and display the product
    display(Math('v^Tw=%g'%np.dot(v,w)))

In [15]:
v1 = np.random.randn(1,10)
v2 = np.random.randn(1,10)

print(np.shape(v1))

(1, 10)


In [16]:
v1 = np.random.randn(1,10)
v2 = np.random.randn(1,10)

print((v1))

[[-1.07835257 -0.74840259  0.12093833 -0.23747715 -1.4374963   1.4403674
  -1.99648235 -0.18257428  0.13498843 -0.27822948]]


In [20]:
v1 = np.random.randn(5,10)
v2 = np.random.randn(1,10)

v1 = np.squeeze(v1)

print(np.shape(v1))

(5, 10)


In [21]:
def myDotProduct(v,w):

    v = np.squeeze(v)
    w = np.squeeze(w)

    #test whether the dot is defined
    if len(v)!=len(w):
        raise ValueError('Vector must have the same length!!')
    
    # compute and display the product
    display(Math('v^Tw=%g'%np.dot(v,w)))

In [26]:
v1 = np.random.randn(1,10)
v2 = np.random.randn(1,10)

print(np.shape(v1))

myDotProduct(v1,v2)

(1, 10)


<IPython.core.display.Math object>